// milestones/milestone4/onotes-app/src/app/note-display/note-display.component.ts
import {Component, inject} from '@angular/core';
import {ActivatedRoute, Router, RouterLink} from '@angular/router';
import {NoteService} from '../service/note.service';
import {Note} from '../model/note.model';
import {FormControl, FormGroup, ReactiveFormsModule, Validators} from '@angular/forms';

@Component({
  selector: 'app-note-display',
  imports: [
    ReactiveFormsModule,
    RouterLink,
  ],
  templateUrl: './note-display.component.html',
  styleUrl: './note-display.component.css'
})
export class NoteDisplayComponent {

  route: ActivatedRoute = inject(ActivatedRoute);
  noteService: NoteService = inject(NoteService);

  noteId: string | null = this.route.snapshot.paramMap.get('id');
  note: Note | null = null;
  formattedCreated: Date | null = null;
  formattedUpdated: Date | null = null;

  noteForm = new FormGroup({
    title: new FormControl('', [Validators.required]),
    content: new FormControl(''),
  });

  constructor(private router: Router) {
    this.noteService.getNoteById(this.noteId, (note: Note) => {
      this.note = note;
      this.formatDates();

      this.noteForm.setValue({
        title: note.title,
        content: note.content,
      });

      const textarea = document.getElementById('content') as HTMLTextAreaElement;
      textarea.style.height = 'auto';
      textarea.style.height = textarea.scrollHeight + 'px';
    });
  }

  handleSubmit() {
    if (this.note && this.noteForm.valid)
    {
      this.note.title = this.noteForm.value.title?.toString() || '';
      this.note.content = this.noteForm.value.content?.toString() || '';
    }

    this.noteService.updateNote(this.note, () => {});
    this.refreshNote();
  }

  autoGrow(event: Event) {
    const textarea = event.target as HTMLTextAreaElement;
    textarea.style.height = 'auto';
    textarea.style.height = textarea.scrollHeight + 'px';
  }


  private refreshNote(): void {
    this.noteService.getNoteById(this.noteId, (note: Note) => {
      this.note = note;
      this.formatDates();
    });
  }

  private formatDates(): void {
    if (this.note) {
      this.formattedCreated = new Date(this.note.created);
      this.formattedUpdated = new Date(this.note.updated);
    }
  }

  handleDelete() {
    this.noteService.deleteNote(this.noteId, () => {});
    this.router.navigate(['/'])
  }
}

<div class="p-3">
  <form [formGroup]="noteForm" (ngSubmit)="handleSubmit()">
    <div class="position-sticky top-0 bg-body">
      <div class="note-menu">
        <a class="note-menu-item" routerLink="/">
          <span class="material-symbols-outlined mt-1">keyboard_backspace</span>
        </a>
        <button class="note-menu-item" type="submit">
          <span class="material-symbols-outlined mt-1">save</span>
        </button>
        <button class="note-menu-item" type="button" data-bs-toggle="modal" data-bs-target="#deleteModal">
          <span class="material-symbols-outlined mt-1">delete</span>
        </button>
        <span class="note-menu-item">Last saved {{ formattedUpdated?.toLocaleString() }}</span>
      </div>
      <hr />
    </div>
    <input class="note-display h1" type="text" formControlName="title" placeholder="Title"/>
    <textarea id="content" class="note-display note-content" formControlName="content" rows="1" (input)="autoGrow($event)" placeholder="Content"></textarea>
  </form>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="deleteModalLabel">Delete note</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete this note?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal" (click)="handleDelete()">Delete</button>
      </div>
    </div>
  </div>
</div>

// milestones/milestone5/onotes-app/src/components/NoteDisplay/NoteDisplay.tsx
import {ChangeEvent, FormEvent, useCallback, useEffect, useState} from "react";
import {createNote, deleteNote, getNote, updateNote} from "../../service/NoteService.ts";
import {Link, useNavigate, useParams} from "react-router";
import {MarkdownService} from "../../service/MarkdownService.ts";
import "./NoteDisplay.css"

function NoteDisplay(props: {modify: boolean}) {
    const [note, setNote] = useState({id: "", title: "", content: "", updated: "", created: ""});
    const [formattedUpdated, setFormattedUpdated] = useState<Date>(new Date())
    const [saved, setSaved] = useState(true);
    const [preview, setPreview] = useState(false);
    const {noteId} = useParams();
    const navigate = useNavigate();


    const fetchNote = useCallback(async () => {
        try {
            const data = await getNote(noteId!.toString());
            setNote(data);
            setFormattedUpdated(new Date(note.updated));
        } catch (error) {
            console.error("Error fetching note", error);
        }
    }, [note.updated, noteId])

    useEffect(() => {
        if (props.modify)
        {
            fetchNote();
            autoGrow();
        }
    }, [fetchNote, props.modify]);

    const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        if (props.modify) {
            updateNote(note).then(fetchNote);
            setSaved(true);
        }
        else {
            createNote(note).then(() => navigate("/"));
        }
    }

    const handleChange = (e: ChangeEvent<HTMLInputElement> | ChangeEvent<HTMLTextAreaElement>) => {
        const name = e.target.name;
        const value = e.target.value;
        setNote({
            ...note,
            [name]: value
        });
        autoGrow();
        setSaved(false);
    }

    function handleDelete() {
        deleteNote(noteId!).then(() => navigate("/"))
    }

    function autoGrow() {
        const textarea = document.getElementById("noteContent") as HTMLTextAreaElement;
        if (textarea) {
            textarea.style.height = 'auto'; // Reset height
            textarea.style.height = textarea.scrollHeight + 'px'; // Adjust to content height
        }
    }

    function handleEditView() {
        setPreview(false);
        setTimeout(autoGrow, 0);
    }

    return (
        <>
            <form onSubmit={handleSubmit}>
                <div className={"position-sticky top-0 bg-body shadow-sm d-flex align-items-center"}>
                    <div className={"btn-group m-1"}>
                        <Link to={"/"} className={"btn btn-outline-dark"}>
                            <i className={"bx bx-arrow-back"}></i>
                        </Link>
                        <button className={"btn btn-outline-dark"} type={"submit"}>
                            <i className={"bx bx-save"}></i>
                        </button>
                        {
                            props.modify &&
                            (<button className={"btn btn-outline-dark"} type={"button"} data-bs-toggle={"modal"}
                                     data-bs-target={"#deleteModal"}>
                                <i className={"bx bx-trash"}></i>
                            </button>)
                        }
                    </div>
                    <input placeholder={"Title"} className={"m-1 note-title text-dark border border-dark rounded-2"}
                           onChange={handleChange} type={"text"}
                           name={"title"} value={note.title}/>
                    <div className={"btn-group m-1"}>
                        <button className={"btn btn-outline-dark" + (preview ? " active" : "")} type={"button"}
                                onClick={() => setPreview(true)}>
                            <i className={"bx bx-show-alt"}></i>
                        </button>
                        <button className={"btn btn-outline-dark" + (preview ? "" : " active")} type={"button"}
                                onClick={handleEditView}>
                            <i className={"bx bx-pencil"}></i>
                        </button>
                    </div>
                    {props.modify && (<div
                        className={"m-1 text-secondary last-saved"}>Last
                        saved {formattedUpdated.toLocaleString()}{saved ? "" : "*"}</div>)}
                </div>
                <div className={"p-3"}>
                    {preview ?
                        <div>
                            <div dangerouslySetInnerHTML={{__html: MarkdownService.parseMd(note.content)}}/>
                        </div>
                        :
                        <div>
                            <textarea placeholder={"Write here..."} onLoad={autoGrow} id={"noteContent"} className={"note-content font-monospace"} onChange={handleChange} name={"content"} value={note.content}/>
                        </div>
                    }
                </div>
            </form>

            <div className={"modal fade"} id={"deleteModal"} tabIndex={-1} aria-labelledby={"deleteModalLabel"} aria-hidden={"true"}>
                <div className={"modal-dialog"}>
                    <div className={"modal-content"}>
                        <div className={"modal-header"}>
                            <h1 className={"modal-title fs-5"} id={"deleteModalLabel"}>Delete note</h1>
                            <button type={"button"} className={"btn-close"} data-bs-dismiss={"modal"} aria-label={"Close"}></button>
                        </div>
                        <div className={"modal-body"}>
                            <p>Are you sure you want to delete this note? This action cannot be undone.</p>
                        </div>
                        <div className={"modal-footer"}>
                            <button type={"button"} className={"btn btn-outline-dark"} data-bs-dismiss={"modal"}>Cancel</button>
                            <button type={"button"} className={"btn btn-outline-danger"} data-bs-dismiss={"modal"} onClick={handleDelete}>Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default NoteDisplay;
