// milestones/milestone4/onotes-app/src/app/note-card/note-card.component.ts
import {Component, Input} from '@angular/core';
import {Note} from '../model/note.model';
import {RouterLink} from '@angular/router';
import {marked} from 'marked';

@Component({
  selector: 'app-note-card',
  imports: [
    RouterLink
  ],
  templateUrl: './note-card.component.html',
  styleUrl: './note-card.component.css'
})
export class NoteCardComponent {
  @Input() note: Note = {id: '', title: '', content: '', created: '', updated: ''};
  protected readonly marked = marked;
}

<a class="card shadow-sm" routerLink="/note/{{ note.id }}">
    <div class="card-body">
      <h5 class="card-title">{{ note.title }}</h5>
      <p class="card-text" [innerHTML]="marked.parse(note.content)"></p>
    </div>
</a>

// milestones/milestone5/onotes-app/src/components/NoteCard/NoteCard.tsx
import './NoteCard.css'
import {Note} from "../../model/Note.ts";
import {Link} from "react-router";
import {MarkdownService} from "../../service/MarkdownService.ts";

function NoteCard(props: {note: Note}) {
    return (
        <Link className={"router-link card shadow-sm"} to={`/notes/${props.note.id}`}>
            <div className={"fixed-height card-body"}>
                <h5 className={"card-title"}>{props.note.title}</h5>
                <div className={"card-text"} dangerouslySetInnerHTML={{ __html: MarkdownService.parse(props.note.content) }}></div>
            </div>
        </Link>
    )
}

export default NoteCard;
