// milestones/milestone4/onotes-app/src/app/navbar/navbar.component.ts
import { Component } from '@angular/core';
import {Router, RouterLink} from '@angular/router';
import {FormControl, FormGroup, ReactiveFormsModule, Validators} from '@angular/forms';

@Component({
  selector: 'app-navbar',
  imports: [
    RouterLink,
    ReactiveFormsModule,
  ],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  constructor(private router: Router) {
  }

  searchForm = new FormGroup({
    search: new FormControl('', [Validators.required]),
  });

  handleSearch() {
    if (this.searchForm.valid) {
      this.router.navigateByUrl('/search/' + this.searchForm.value.search);
    }
  }
}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" routerLink="/">All Notes</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" routerLink="about">About</a>
        </li>
      </ul>
      <form class="d-flex" role="search" [formGroup]="searchForm" (ngSubmit)="handleSearch()">
        <input class="form-control me-2" formControlName="search" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

// milestones/milestone5/onotes-app/src/components/Navbar/Navbar.tsx
import {ChangeEvent, FormEvent, useState} from "react";

function Navbar() {
    const [search, setSearch] = useState({keyword: ""});

    const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
        const name = e.target.name
        const value = e.target.value
        setSearch({
            ...search,
            [name]: value
        });
    }

    const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        console.log(search)
        window.location.assign('/search/' + search.keyword);
    }

    return (
        <nav className={"navbar fixed-top navbar-expand-lg bg-body border-bottom"}>
            <div className={"container-fluid"}>
                <a href={"/"} className={"navbar-brand"}>
                    <i className='bx bx-note'></i>
                </a>
                <button className="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="navbarSupportedContent">
                    <form className="d-flex" role="search" onSubmit={handleSubmit}>
                        <input name={"keyword"} className="form-control me-2" type="search" placeholder="Search Notes" aria-label="Search" onChange={handleChange}/>
                        <button className="btn btn-outline-dark" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    )
}

export default Navbar
